name: Testim E2E
on: [push]

jobs:
    run-testimio-cli:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '16.13.0'
            - run: npm install -g @testim/testim-cli
            
            - run: testim --token "HFPMMWmDBgphmMFNcfS4oxVts7JPyZChVl1rYgGXBPs5pkKT8C" --project "8iuIg6jOYNgj5YnNs5RJ" --grid "Testim-Grid" --name "1 - Login" --report-file testim-report.xml
